### ISSUE TITLE
REST API Design

### ISSUE THREAD

**Issue by MaximPedich** [MaximPedich/crawler-gd#1]
- Дизайн REST API ресурсов;
- Дизайн REST API эндпоинтов;
- Дизайн сущности запросов/ответов;

**Критерии приемки (Acceptance Criteria):**
- Список эндпоинтов, с указанием методов и параметров (контракт);
- Описание сущностей (запросов/ответов) в json формате (контракт);

**Comment by AlexShylin** [comment]
1) scan/{url}?thrd={val}&delay={val} - запускает краулер; обращается к сервису ScanService в метод inspect(String url, int threadsNum, long delay)
2) /res/{id}/{sort}/n-m - получение результата по id; {sort} - asc. desc; n-m - id ссылок от и до; /{sort}/n-m - необязательная часть; обращаемся к ResultService в getResult(long id, long from, long to, String sortingAcsDesc)
3) /res/{id}/concrete/{id} - получение результата проверки конкретной ссылки; обращаемся к ResultService в getConcreteScan(long id, long scanId)
4) /suspend/{id} - остановка по id; обращаемся в ScanService по suspend(long id)
5) /status/{id} - статус по id; ResultService.scan(long id)
6) /health

**Comment by MaximPedich** [comment]
> scan/{url}?thrd={val}&delay={val} - запускает краулер; обращается к сервису ScanService в метод inspect(String url, int threadsNum, long delay)
> /res/{id}/{sort}/n-m - получение результата по id; {sort} - asc. desc; n-m - id ссылок от и до; /{sort}/n-m - необязательная часть; обращаемся к ResultService в getResult(long id, long from, long to, String sortingAcsDesc)
> /res/{id}/concrete/{id} - получение результата проверки конкретной ссылки; обращаемся к ResultService в getConcreteScan(long id, long scanId)
> /suspend/{id} - остановка по id; обращаемся в ScanService по suspend(long id)
> /status/{id} - статус по id; ResultService.scan(long id)
> /health - как и было; HelthService.healthCheck()

Предлагаю следовать этим рекомендациям -- http://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/

Предлагаю использовать эти понятия:

- https://en.wikipedia.org/wiki/Web_crawler (Краулер) -- ответственен за обход сайта;
-  https://en.wikipedia.org/wiki/Web_scraping (Скрапер) -- ответственен за извлечение данных (ссылок) по страницы;

1. Названия ресурсов должны быть имена существительные в множественном числе. То есть:
/crawlers

2. GET методы не должны менять состояния. Получается нельзя запускать задание на краулинг сайта с использованием GET метода. Остаются варианты PUT, POST. О их различии можно почитать [здесь](http://stackoverflow.com/questions/107390/whats-the-difference-between-a-post-and-a-put-http-request). Я бы советовал использовать POST, поскольку он не идемпотентен (то есть, нельзя разместить задание на сканирование сайта, если оно в данный момент выполняется).
Получается 
POST /crawlers 
с CrawlerTask сущностью в теле запроса, где будут указываться: url, threads, delay.

8. Нужно версионировать API, что бы была возможность выпускать разные версии ресурсов и поддерживать обратную совместимость (https://en.wikipedia.org/wiki/Backward_compatibility)
Получается
POST /v1/crawlers с CrawlerTask сущностью в теле запроса, где будут указываться: url, delay.
POST /v2/crawlers с CrawlerTask сущностью в теле запроса, где будут указываться: url, delay, threads.

9. Нужно продумать формат для возврата ошибок. Например, пользователь указал не валидный URL, или внутренняя ошибка во время работы краулера. HTTP ответы должны возвращать соответствующий HTTP-статус код.
Пример
{
  "errors": [
   {
    "userMessage": "Sorry, the requested resource does not exist",
    "internalMessage": "No car found in the database",
    "code": 34,
    "more info": "http://dev.mwaysolutions.com/blog/api/v1/errors/12345"
   }
  ]
}&nbsp;

**Comment by MaximPedich** [comment]
Еще один вариант, взять в качестве примера один из популярных REST API.

https://www.quora.com/What-is-a-good-real-life-example-of-a-truly-RESTful-API

Например, Pay-Pal --  https://developer.paypal.com/docs/api/

**Comment by MaximPedich** [comment]
Еще несколько уточнений.

Для создания crawler-job лучше использовать POST с параметрами в теле запроса, а не path params. 
https://developer.paypal.com/docs/api/payments.billing-plans#plan_create

Для изменения состояния crawler-job, лучше использовать PATCH https://developer.paypal.com/docs/api/payments.billing-plans#plan_update

**Comment by AlexShylin** [comment]
https://docs.google.com/a/griddynamics.com/document/d/134Swy87pgHaCF8N66vOvDPRE2jfU4tB6MUTpg2J2rfw/edit?usp=sharing
