### ISSUE TITLE
First implementation of crawler (single thread)

### ISSUE THREAD

**Issue by MaximPedich** [MaximPedich/crawler-gd#2]
Реализовать однопоточный краулер с REST API для скрапинга недействительных ссылок на заданном  сайте.

У приложения должны быть следующие функции:
Запуск задания на обход сайта с возможностью указать параметры запуска: количество потоков доступных для сканирования сайта, задержка между запросами на сайт; 
Результат сканирования сайта -- список недействительных ссылок на сайте (как внутренних так и внешних).
У пользователя должна быть возможность в любой момент запросить результат сканирования сайта, по полученному, во время создания задания, ключу. При запросе результатов сканирования сайта должна быть возможность указать: количество элементов в ответе, сортировка. Результаты ответа сервиса не должны пересекаться;
У пользователя должна быть возможность остановить задание;
У пользователя должна быть возможность запросить статус задания (подразумевается что сам результат работы краулера не будет возвращен в подобном запросе);
Health ресурс, возвращаемый статус готовности к работе приложения;

Все выполненные задания должны храниться в БД. 

Результат выполнения задания должен содержать:
ИД
Статус: завершено | остановлено | выполняется
Дата запуска
Дата окончания
Адрес сканируемого сайта
Параметры сканирования (во сколько потоков, сколько была задержка между запросами и т.д.)
Результат сканирования

Ссылки:

1. http://stackoverflow.com/questions/30580562/what-is-the-difference-between-resource-and-endpoint

**Comment by AlexShylin** [comment]
залил - http://ec2-54-69-159-74.us-west-2.compute.amazonaws.com/#/q/status:open
проверено на:
1.  http://marklamb.com/ (~30 seconds)
2.  http://kbroman.org/ (~10 minutes)
