### ISSUE TITLE
Перенести исходный код в gerrit

### ISSUE THREAD

**Issue by MaximPedich** [MaximPedich/crawler-gd#3]
Использовать эту [инструкцию](https://docs.google.com/document/d/1H7Z2dF8WUhbbPUZiJe6l7tVthMZ5vxFLjK85xVSlkZ8/edit)

Критерии приемки (acceptance criteria):
-- Весь исходный код размещен на сервере -- http://ec2-54-69-159-74.us-west-2.compute.amazonaws.com/#/q/status:open

Теперь нужно вести разработку в gerrit.

**Acceptance criteria**
Добавленная в комментарии ссылку на проект в gerrit.

**Comment by AlexShylin** [comment]
http://ec2-54-69-159-74.us-west-2.compute.amazonaws.com/#/admin/projects/ashylin

**Comment by AlexShylin** [comment]
проект - http://ec2-54-69-159-74.us-west-2.compute.amazonaws.com/#/admin/projects/ashylin
список коммитов - http://ec2-54-69-159-74.us-west-2.compute.amazonaws.com/#/dashboard/self
