### ISSUE TITLE
REST API documentation

### ISSUE THREAD

**Issue by MaximPedich** [MaximPedich/crawler-gd#4]
Задокументировать существующий REST API.
Пример https://developer.paypal.com/docs/api/payments.billing-agreements/#agreement_create

Acceptance criteria:
-- документ в google docs. Ссылку добавить в комментарии к этой issue.

**Comment by AlexShylin** [comment]
https://docs.google.com/a/griddynamics.com/document/d/134Swy87pgHaCF8N66vOvDPRE2jfU4tB6MUTpg2J2rfw/edit?usp=sharing
