### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by MaximPedich** [MaximPedich/crawler-gd#5]
Покрыть функциональность краулера модульными тестами. 
Использовать JUnit и Mockito.

Разобраться в теории:

- Что такое модульное тестирование и какой принцип написания подобного теста?
- Что такое интеграционное тестирование и какой принцип написания подобного теста?
- Что такое функциональное тестирование и какой принцип написания подобного теста?
- Что такое мок и стаб, в чем их отличие ?
- Что такое фикстура?

**Comment by AlexShylin** [comment]
http://ec2-54-69-159-74.us-west-2.compute.amazonaws.com/#/c/164/
