### ISSUE TITLE
Сделать свою реализацию кеша

### ISSUE THREAD

**Issue by MaximPedich** [MaximPedich/crawler-gd#6]
Имплементировать интерфейс

    public interface Cache<K, V> {

        V getIfPresent(Object key);

        void put(K key, V value);

        void invalidate(K key);

        void invalidateAll();

        long size();

        CacheStats stats(); -- пока бросать UnsupportedOperationException()
    }

Сделать клиент и сервер на сокетах.

**Comment by AlexShylin** [comment]
http://ec2-54-69-159-74.us-west-2.compute.amazonaws.com/#/c/209/
